apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  namespace: tracing
  labels:
    app: jaeger-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jaeger-collector
  template:
    metadata:
      labels:
        app: jaeger-collector
    spec:
      containers:
      - name: jaeger-collector
        image: jaegertracing/jaeger-collector:1.54
        args:
          - "--span-storage.type=elasticsearch"
          - "--es.server-urls=http://jaeger-elasticsearch:9200"
          - "--es.tags-as-fields.all=true"
          - "--es.num-shards=1"
          - "--es.num-replicas=0"
          - "--collector.otlp.enabled=true"
          - "--collector.zipkin.host-port=:9411"
          - "--collector.grpc-server.host-port=:14250"
          - "--collector.http-server.host-port=:14268"
          - "--log-level=info"
        ports:
        - containerPort: 14268
          name: http
        - containerPort: 14250
          name: grpc
        - containerPort: 9411
          name: zipkin
        - containerPort: 14269
          name: admin
        env:
        - name: SPAN_STORAGE_TYPE
          value: elasticsearch
        - name: ES_SERVER_URLS
          value: http://jaeger-elasticsearch:9200
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: tracing
  labels:
    app: jaeger-collector
spec:
  selector:
    app: jaeger-collector
  ports:
  - port: 14268
    targetPort: 14268
    name: http
  - port: 14250
    targetPort: 14250
    name: grpc
  - port: 9411
    targetPort: 9411
    name: zipkin
  - port: 14269
    targetPort: 14269
    name: admin
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  namespace: tracing
  labels:
    app: jaeger-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-query
  template:
    metadata:
      labels:
        app: jaeger-query
    spec:
      containers:
      - name: jaeger-query
        image: jaegertracing/jaeger-query:1.54
        args:
          - "--span-storage.type=elasticsearch"
          - "--es.server-urls=http://jaeger-elasticsearch:9200"
          - "--es.tags-as-fields.all=true"
          - "--query.base-path=/jaeger"
          - "--query.ui-config=/etc/jaeger/ui-config.json"
          - "--log-level=info"
        ports:
        - containerPort: 16686
          name: ui
        - containerPort: 16687
          name: admin
        env:
        - name: SPAN_STORAGE_TYPE
          value: elasticsearch
        - name: ES_SERVER_URLS
          value: http://jaeger-elasticsearch:9200
        volumeMounts:
        - name: ui-config
          mountPath: /etc/jaeger/ui-config.json
          subPath: ui-config.json
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 16687
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 16687
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: ui-config
        configMap:
          name: jaeger-ui-config
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: tracing
  labels:
    app: jaeger-query
spec:
  selector:
    app: jaeger-query
  ports:
  - port: 16686
    targetPort: 16686
    nodePort: 30004
    name: ui
  - port: 16687
    targetPort: 16687
    name: admin
  type: NodePort
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger-agent
  namespace: tracing
  labels:
    app: jaeger-agent
spec:
  selector:
    matchLabels:
      app: jaeger-agent
  template:
    metadata:
      labels:
        app: jaeger-agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.54
        args:
          - "--reporter.grpc.host-port=jaeger-collector:14250"
          - "--reporter.grpc.retry.max=3"
          - "--agent.tags=deployment.name=jaeger-agent"
          - "--log-level=info"
        ports:
        - containerPort: 6831
          protocol: UDP
          name: jg-compact-trft
        - containerPort: 6832
          protocol: UDP
          name: jg-binary-trft
        - containerPort: 5778
          name: http
        - containerPort: 14271
          name: admin
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 14271
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 14271
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: tracing
  labels:
    app: jaeger-agent
spec:
  selector:
    app: jaeger-agent
  ports:
  - port: 6831
    targetPort: 6831
    protocol: UDP
    name: jg-compact-trft
  - port: 6832
    targetPort: 6832
    protocol: UDP
    name: jg-binary-trft
  - port: 5778
    targetPort: 5778
    name: http
  - port: 14271
    targetPort: 14271
    name: admin
  type: ClusterIP