# Loki 로그 수집 서비스

networks:
  meritz-network:
    external: true

volumes:
  loki_data:

services:
  # Loki (로그 수집)
  loki:
    image: grafana/loki:2.9.0
    container_name: meritz-loki
    restart: unless-stopped
    ports:
      - "10003:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
      - ./config:/etc/loki
    networks:
      - meritz-network
    environment:
      - TZ=Asia/Seoul
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki.meritz.com`)"
      - "traefik.http.routers.loki.tls.certresolver=letsencrypt"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
      - "traefik.http.routers.loki.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$10$$2b2cu2Fw10/ZfDdQh2hkS.uY2WM4jhP6K6K9b6OOFqI7OOgHv7hhu"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
