# Prometheus 설정 파일
# Meritz Gateway 모니터링 구성

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'meritz-gateway'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Traefik 메트릭
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Node Exporter (시스템 메트릭)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor (컨테이너 메트릭)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Grafana 메트릭
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Docker 컨테이너 서비스 디스커버리
  - job_name: 'docker-services'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        target_label: __tmp_prometheus_job_name
      - source_labels: [__tmp_prometheus_job_name]
        regex: .+
        target_label: job
      - regex: __meta_dockerswarm_service_label_prometheus_job
        action: labeldrop

  # 웹 서비스 헬스체크 (blackbox exporter)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://meritz.com
        - https://www.meritz.com
        - https://api.meritz.com
        - https://admin.meritz.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # 업타임 체크
  - job_name: 'uptime-kuma'
    static_configs:
      - targets: ['uptime-kuma:3001']
    scrape_interval: 60s
    metrics_path: '/metrics'

# 원격 쓰기 설정 (선택적)
# remote_write:
#   - url: "https://prometheus-remote-write.meritz.com/api/v1/write"
#     headers:
#       Authorization: "Bearer <token>"

# 원격 읽기 설정 (선택적)
# remote_read:
#   - url: "https://prometheus-remote-read.meritz.com/api/v1/read"
#     headers:
#       Authorization: "Bearer <token>"
