# Jaeger 분산 트레이싱 서비스

networks:
  meritz-network:
    external: true

volumes:
  jaeger_data:

services:
  # Jaeger (분산 트레이싱)
  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: meritz-jaeger
    restart: unless-stopped
    ports:
      - "10004:16686"  # UI
      - "10005:14268"  # HTTP collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory
      - TZ=Asia/Seoul
    volumes:
      - jaeger_data:/tmp
    networks:
      - meritz-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.meritz.com`)"
      - "traefik.http.routers.jaeger.tls.certresolver=letsencrypt"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
      - "traefik.http.routers.jaeger.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$10$$2b2cu2Fw10/ZfDdQh2hkS.uY2WM4jhP6K6K9b6OOFqI7OOgHv7hhu"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:16686/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
