version: '3.8'

services:
  # Keycloak용 PostgreSQL
  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    ports:
      - "10901:5432"
    networks:
      - security-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "description=Keycloak PostgreSQL 데이터베이스"

  # Keycloak 인증 서버
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    restart: unless-stopped
    command:
      - start-dev
      - --hostname-strict=false
      - --hostname-strict-https=false
      - --proxy=edge
      - --http-enabled=true
      - --import-realm
    environment:
      # 데이터베이스 설정
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      
      # 관리자 계정
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      
      # 기타 설정
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 8080
      KC_PROXY: edge
      KC_LOG_LEVEL: INFO
      
      # JVM 옵션
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    volumes:
      - ./config/keycloak/themes:/opt/keycloak/themes:ro
      - ./config/keycloak/providers:/opt/keycloak/providers:ro
      - ./config/keycloak/import:/opt/keycloak/data/import:ro
      - keycloak-data:/opt/keycloak/data
    ports:
      - "10900:8080"
    networks:
      - security-network
    depends_on:
      keycloak-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      - "description=Keycloak 인증 서버"
      - "service.type=authentication"

  # HashiCorp Vault
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: vault-root-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_API_ADDR: http://localhost:10902
      VAULT_ADDRESS: http://localhost:8200
      VAULT_UI: "true"
      VAULT_LOG_LEVEL: INFO
    command:
      - vault
      - server
      - -dev
      - -dev-root-token-id=vault-root-token
      - -dev-listen-address=0.0.0.0:8200
    volumes:
      - ./config/vault/config:/vault/config:ro
      - ./config/vault/policies:/vault/policies:ro
      - ./config/vault/data:/vault/data
      - vault-data:/vault/file
    ports:
      - "10902:8200"
    networks:
      - security-network
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "description=HashiCorp Vault 시크릿 관리"
      - "service.type=secret-management"

  # Vault UI (선택사항)
  vault-ui:
    image: djenriquez/vault-ui:latest
    container_name: vault-ui
    restart: unless-stopped
    environment:
      VAULT_URL_DEFAULT: http://vault:8200
      VAULT_AUTH_DEFAULT: TOKEN
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    ports:
      - "10903:8000"
    networks:
      - security-network
    depends_on:
      - vault
    labels:
      - "description=Vault 웹 UI"
      - "service.type=ui"

  # Keycloak 설정 초기화 도구
  keycloak-config:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak-config
    restart: "no"
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin123
    volumes:
      - ./config/keycloak/realm-config:/tmp/realm-config:ro
      - ./scripts:/scripts:ro
    networks:
      - security-network
    depends_on:
      keycloak:
        condition: service_healthy
    command: |
      sh -c "
        echo 'Keycloak 초기 설정 시작...'
        sleep 30
        /scripts/setup-keycloak.sh
        echo 'Keycloak 초기 설정 완료!'
      "
    labels:
      - "description=Keycloak 초기 설정 도구"

  # Vault 설정 초기화 도구
  vault-config:
    image: hashicorp/vault:1.15
    container_name: vault-config
    restart: "no"
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: vault-root-token
    volumes:
      - ./scripts:/scripts:ro
    networks:
      - security-network
    depends_on:
      vault:
        condition: service_healthy
    command: |
      sh -c "
        echo 'Vault 초기 설정 시작...'
        sleep 15
        /scripts/setup-vault.sh
        echo 'Vault 초기 설정 완료!'
      "
    labels:
      - "description=Vault 초기 설정 도구"

volumes:
  keycloak-db-data:
    driver: local
    labels:
      - "description=Keycloak PostgreSQL 데이터"
  keycloak-data:
    driver: local
    labels:
      - "description=Keycloak 애플리케이션 데이터"
  vault-data:
    driver: local
    labels:
      - "description=Vault 파일 스토리지"

networks:
  security-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
    labels:
      - "description=보안 서비스 네트워크"

# 환경 변수 설정
x-common-environment: &common-env
  TZ: Asia/Seoul
  LANG: ko_KR.UTF-8
