# cAdvisor 컨테이너 메트릭 수집 서비스

networks:
  meritz-network:
    external: true

services:
  # cAdvisor (컨테이너 메트릭)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: meritz-cadvisor
    restart: unless-stopped
    ports:
      - "10007:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    networks:
      - meritz-network
    environment:
      - TZ=Asia/Seoul
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
