# Promtail 로그 에이전트 설정
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://meritz-loki:3100/loki/api/v1/push

scrape_configs:
  # 시스템 로그
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/*log

  # Docker 컨테이너 로그
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag: attrs.tag
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # Traefik 액세스 로그
  - job_name: traefik-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: traefik-access
          __path__: /traefik/logs/access.log
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            msg: msg
            remote_addr: ClientAddr
            method: RequestMethod
            url: RequestPath
            status: DownstreamStatus
            response_time: Duration
            user_agent: RequestUserAgent
      - labels:
          level:
          method:
          status:
      - timestamp:
          format: RFC3339
          source: time

  # 커스텀 애플리케이션 로그
  - job_name: applications
    static_configs:
      - targets:
          - localhost
        labels:
          job: applications
          __path__: /var/log/apps/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: "@timestamp"
            level: level
            logger: logger
            message: message
            service: service.name
            trace_id: trace.id
            span_id: span.id
      - labels:
          level:
          service:
          logger:
      - timestamp:
          format: RFC3339
          source: timestamp
