# Uptime Kuma 가용성 모니터링 서비스
version: '3.8'

networks:
  meritz-network:
    external: true

services:
  # Uptime Kuma (헬스체크 모니터링)
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.0
    container_name: meritz-uptime-kuma
    restart: unless-stopped
    ports:
      - "10008:3001"
    volumes:
      - ./data:/app/data
    networks:
      - meritz-network
    environment:
      - TZ=Asia/Seoul
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`uptime.meritz.com`)"
      - "traefik.http.routers.uptime.tls.certresolver=letsencrypt"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3001/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
