# Node Exporter 시스템 메트릭 수집 서비스
version: '3.8'

networks:
  meritz-network:
    external: true

services:
  # Node Exporter (시스템 메트릭)
  node-exporter:
    image: prom/node-exporter:v1.6.0
    container_name: meritz-node-exporter
    restart: unless-stopped
    ports:
      - "10006:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - meritz-network
    environment:
      - TZ=Asia/Seoul
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9100/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
