# Promtail 로그 에이전트 설정
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # 시스템 로그
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/*log

  # Docker 컨테이너 로그
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag: attrs.tag
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # Traefik 액세스 로그
  - job_name: traefik-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: traefik-access
          __path__: /traefik/logs/access.log
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            msg: msg
            remote_addr: ClientAddr
            method: RequestMethod
            url: RequestPath
            status: DownstreamStatus
            response_time: Duration
            user_agent: RequestUserAgent
      - labels:
          level:
          method:
          status:
      - timestamp:
          format: RFC3339
          source: time

  # Traefik 애플리케이션 로그
  - job_name: traefik-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: traefik-app
          __path__: /traefik/logs/traefik.log
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            msg: msg
      - labels:
          level:
      - timestamp:
          format: RFC3339
          source: time

  # Nginx 로그 (기본 서비스용)
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>.*)\] "(?P<method>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)" (?P<status>[\d]+) (?P<body_bytes_sent>[\d]+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"'
      - labels:
          method:
          status:
          remote_addr:
      - timestamp:
          format: "02/Jan/2006:15:04:05 -0700"
          source: time_local

  # 커스텀 애플리케이션 로그
  - job_name: applications
    static_configs:
      - targets:
          - localhost
        labels:
          job: applications
          __path__: /var/log/apps/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: "@timestamp"
            level: level
            logger: logger
            message: message
            service: service.name
            trace_id: trace.id
            span_id: span.id
      - labels:
          level:
          service:
          logger:
      - timestamp:
          format: RFC3339
          source: timestamp

# 로그 라벨링 규칙
- job_name: kubernetes-pods
  kubernetes_sd_configs:
    - role: pod
  relabel_configs:
    - source_labels:
        - __meta_kubernetes_pod_node_name
      target_label: __host__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      replacement: $1
      separator: /
      source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_name
      target_label: job
    - action: replace
      source_labels:
        - __meta_kubernetes_namespace
      target_label: namespace
    - action: replace
      source_labels:
        - __meta_kubernetes_pod_name
      target_label: pod
    - action: replace
      source_labels:
        - __meta_kubernetes_pod_container_name
      target_label: container
    - replacement: /var/log/pods/*$1/*.log
      separator: /
      source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
      target_label: __path__
