# Promtail 로그 에이전트 서비스
version: '3.8'

networks:
  meritz-network:
    external: true

services:
  # Promtail (로그 에이전트)
  promtail:
    image: grafana/promtail:2.9.0
    container_name: meritz-promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./config:/etc/promtail
      - ../gateway/traefik/logs:/traefik/logs:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - meritz-network
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - loki
    external_links:
      - meritz-loki:loki
