# Traefik 메인 설정 파일
# *.meritz.com 도메인 라우팅을 위한 Gateway 설정

# 전역 설정
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API 및 대시보드 설정
api:
  dashboard: true
  debug: false
  insecure: false

# 엔트리포인트 설정 (HTTP/HTTPS)
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        options: default

# 인증서 해결자 (Let's Encrypt)
certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      email: admin@meritz.com
      storage: /ssl/acme.json
      # 스테이징 환경에서 테스트
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory

# 프로바이더 설정
providers:
  # 파일 기반 설정
  file:
    directory: /config/dynamic
    watch: true
  
  # Docker 프로바이더
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: meritz-network
    watch: true

# 로그 설정
log:
  level: INFO
  filePath: /logs/traefik.log
  format: json

# 액세스 로그
accessLog:
  filePath: /logs/access.log
  format: json
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Authorization: drop
        Content-Type: keep

# 메트릭 설정 (Prometheus)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# 핑 설정 (헬스체크)
ping:
  entryPoint: traefik

# 서버 전송 설정
serversTransport:
  insecureSkipVerify: true
  maxIdleConnsPerHost: 7
  forwardingTimeouts:
    dialTimeout: 30s
    responseHeaderTimeout: 0s
    idleConnTimeout: 90s

# 트레이싱 설정 (선택적)
# tracing:
#   jaeger:
#     samplingParam: 1.0
#     samplingType: const
#     localAgentHostPort: "jaeger:6831"
